name: angular_material
version: 0.2.0
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Material Design implementation on Angular Dart.
homepage: https://github.com/akserg/angular.dart.material
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  angular: '>=1.1.0 <2.0.0'
  less_dart: ">=0.1.4 <0.2.0"
dev_dependencies:
  dartmocks: '>= 0.5.0'
  guinness: '>= 0.1.3'
transformers:
  - less_dart:
      entry_point: web/less/ripples.less
      output: web/css/ripples.css
  - less_dart:
      entry_point: web/less/material-wfont.less
      include_path: web/less
      output: web/css/material-wfont.css
  - angular:
      html_files:
        - web/index.html