name: angular_material
version: 0.6.6
author: Sergey Akopkokhyants <akserg@gmail.com>
description: Material Design implementation on Angular Dart.
homepage: https://github.com/akserg/angular.dart.material
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  angular: '>=1.1.0 <2.0.0'
  angular_ui: '>=0.6.6 <0.7.0'
  less_dart: ">=0.1.4 <0.2.0"
dev_dependencies:
  dartmocks: '>= 0.5.0'
  guinness: '>= 0.1.3'
transformers:
- angular:
    html_files:
      - web/index.html
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]